using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

public enum CCD_GRAB_MODE
{
	CCD_GRAB_STOP = 0, 
	CCD_GRAB_LIVE
}
public enum EOUTMODE
{
	OUTMODE_BAYER_BGGR = 1, // Bayer
	OUTMODE_BAYER_RGGB,
	OUTMODE_BAYER_GBRG,
	OUTMODE_BAYER_GRBG,
	OUTMODE_BAYER_BLACKWHITE,
	OUTMODE_YUV422_YCbYCr = 1, // YUV422
	OUTMODE_YUV422_YCrYCb = 2,
	OUTMODE_YUV422_CbYCrY = 3,
	OUTMODE_YUV422_CrYCbY = 4,
	OUTMODE_RGB_BGR = 1, // RGB
	OUTMODE_RGB_RGB = 2,
	OUTMODE_BAYER_BNGR = 1, // RGB-IR Uniform pattern
	OUTMODE_BAYER_RGNB,
	OUTMODE_BAYER_NBRG,
	OUTMODE_BAYER_GRBN,
	OUTMODE_BAYER_BGGN = 1, // RGB-IR Pattern 2
	OUTMODE_BAYER_RGGN,
	OUTMODE_BAYER_GBNG,
	OUTMODE_BAYER_GRNG,
	OUTMODE_BAYER_NGGR,
	OUTMODE_BAYER_NGGB,
	OUTMODE_BAYER_GNRG,
	OUTMODE_BAYER_GNBG,
}

public enum EDATAFORMAT
{
	DATAFORMAT_YUV,
	DATAFORMAT_BAYER_8BIT,
	DATAFORMAT_BAYER_10BIT,
	DATAFORMAT_BAYER_PARALLEL_10BIT,
	DATAFORMAT_BAYER_12BIT,
	DATAFORMAT_BAYER_PARALLEL_12BIT,
	DATAFORMAT_BAYER_16BIT,
	DATAFORMAT_BAYER_16BIT_BE,
	DATAFORMAT_BAYER_16BIT_PWL_HDR,
	DATAFORMAT_BAYER_16BIT_PWL_DECOMP,
	DATAFORMAT_BAYER_24BIT,
	DATAFORMAT_BAYER_PARALLEL_10BIT_BE,
	DATAFORMAT_BAYER_PARALLEL_12BIT_BE,
	DATAFORMAT_RGB = 100,
	DATAFORMAT_INT = 200
}
;

public enum ESENSORTYPE
{
	SENSORTYPE_RGGB = 0,
	SENSORTYPE_RCCC,
	SENSORTYPE_RCCB,
	SENSORTYPE_CCCC,
	SENSORTYPE_RBCC,
	SENSORTYPE_OTHER,
	SENSORTYPE_RGBIR2,
	MAX_COUNT_SENSORTYPE
}

public enum EDEMOSAICMETHOD
{
	DEMOSAICMETHOD_NONE = 0,
	DEMOSAICMETHOD_GRADIENT,
	DEMOSAICMETHOD_BL33, // Bilinear3x3
	DEMOSAICMETHOD_OPENCV_BL,
	DEMOSAICMETHOD_OPENCV_VNG,
	DEMOSAICMETHOD_OPENCV_EA,
	DEMOSAICMETHOD_VNG,  // Variable Number of Gradient
	DEMOSAICMETHOD_GR_ONLY,
	DEMOSAICMETHOD_GB_ONLY,
	DEMOSAICMETHOD_GBTF, // Gradient based Threshold Free
	DEMOSAICMETHOD_BLLC, // Bilinear Laplacian Corrected
	DEMOSAICMETHOD_RESIDUAL, // Residual Interpolation
	DEMOSAICMETHOD_BAYER_Y, // Y = (R + Gr + Gb + B) / 4
	DEMOSAICMETHOD_AHD, // Adaptive Homogeneity-Directed
	DEMOSAICMETHOD_GRADIENT_RESIDUAL = 101, // G(Gradient) + R/B/IR(RI)
	DEMOSAICMETHOD_GBTF_RESIDUAL, // G(GBTF) + R/B/IR(RI)
	DEMOSAICMETHOD_RESIDUAL_RESIDUAL, // G(RI) + R/B/IR(RI)
	DEMOSAICMETHOD_BL33_RESIDUAL, // G(BL33) + R/B/IR(RI)
	DEMOSAICMETHOD_IR_ONLY,
	DEMOSAICMETHOD_GRADIENT_G_ONLY, // G(Gradient)
	DEMOSAICMETHOD_GBTF_G_ONLY, // G(GBTF)
	DEMOSAICMETHOD_RESIDUAL_G_ONLY, // G(RI)
	DEMOSAICMETHOD_BL33_G_ONLY, // G(BL33)
	DEMOSAICMETHOD_GRADIENT_IR_ONLY, // IR(Gradient)
	DEMOSAICMETHOD_GBTF_IR_ONLY, // IR(GBTF)
	DEMOSAICMETHOD_RESIDUAL_IR_ONLY, // IR(RI)
	DEMOSAICMETHOD_BL33_IR_ONLY, // IR(BL33)
	MAX_COUNT_DEMOSAICMETHOD
}


public enum EImageIndex
{
	/* ONSEMI or OVT Sensor */
	EImageIndex_Bright = 0,
	EImageIndex_Dark,
	EMax_ImageIndex_Count,
	/* Sony Sensor */
	EImageIndex_Highlight_SP1L = 0,
	EImageIndex_Highlight_SP2L,
	EImageIndex_Dark_SP1L,
	EImageIndex_Dark_SP2H,
	EImageIndex_Dark_SP2L,
	EImageIndex_Saturated_SP1H,
	EImageIndex_Saturated_SP1L,
	EImageIndex_Saturated_SP2H,
	EImageIndex_Saturated_SP2L,
	EMax_Sony_ImageIndex_Count
}

public enum AlgorithmTestItem
{
	BLEMISH_BLACKSPOT = 0,
	BLEMISH_LCB,
	BLEMISH_FDF,
	BLEMISH_RU_YMEAN,
	RESOLUTION_EIAJ,
	RESOLUTION_SFR2FREQ,
	RESOLUTION_FREQ2SFR,
	OPTICAL_CENTER_CENTROID, // bkkim :: modified due to the duplicated definition
	OPTICAL_CENTER_BRIGHTEST,
	OPTICAL_CENTER_POLYFIT,        // bkkim :: modified due to the duplicated definition
	OPTICAL_CENTER_FIDUCIAL_MARK,  // bkkim :: modified due to the duplicated definition
	SNR_FPN,
	SNR_BW,
	SNR_NORM,
	SNR_DARK_CURRENT,
	SNR_VNE,
	SNR_DARK_NOISE,
	ETC_COLOR_REPRODUCTION,
	ETC_IR_FILTER,
	ETC_COLOR_INTENSITY,
	ETC_FOV,
	ETC_FLARE,
	ETC_VIEW_MODE,
	ETC_SATURATION,
	ETC_STRAY_LIGHT,
	DARK_BRIGHT,
	DARK_DARK,
	DARK_HOT,
	DARK_LINE_NOISE,
	DARK_LOW_LIGHT_DARK,
	DARK_ALL_DEFECT_ONSEMI,
	DARK_ALL_DEFECT_OMS,
	DARK_ALL_DEFECT_OV,
	DARK_ALL_DEFECT_SONY,
	DARK_ALL_DEFECT_RIVIAN,
	SHADING_COLOR_SHADING,
	SHADING_COLOR_SHADING_COMMON,
	SHADING_RELATIVE_ILLUMINATION,
	SHADING_RELATIVE_ILLUMINATION_COMMON,
	SHADING_RELATIVE_ILLUMINATION_X,
	SHADING_RELATIVE_UNIFORMITY,
	SHADING_COLOR_UNIFORMITY,
	SHADING_SHADING_UNIFORMITY,
	SHADING_COLOR_SENSITIVITY,
	SHADING_LENS_SHADING,
	ALGORITHM_TESTITEM_MAX
}
public struct TDATASPEC
{
	public EOUTMODE eOutMode;
	public EDATAFORMAT eDataFormat;
	public ESENSORTYPE eSensorType;
	public EDEMOSAICMETHOD eDemosaicMethod;
	public int nBlackLevel;
}

